
project_id = "cepbomjkpvaoptyuunhx"

[global.env]
SUPABASE_URL = "env:SUPABASE_URL"
SUPABASE_ANON_KEY = "env:SUPABASE_ANON_KEY"
SUPABASE_SERVICE_ROLE_KEY = "env:SUPABASE_SERVICE_ROLE_KEY"
RESEND_API_KEY = "env:RESEND_API_KEY"
TWILIO_ACCOUNT_SID = "env:TWILIO_ACCOUNT_SID"
TWILIO_AUTH_TOKEN = "env:TWILIO_AUTH_TOKEN"
TWILIO_PHONE_NUMBER = "env:TWILIO_PHONE_NUMBER"
