// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cepbomjkpvaoptyuunhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlcGJvbWprcHZhb3B0eXV1bmh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MjQzNjQsImV4cCI6MjA1NDEwMDM2NH0.oMcMy4LPHQEzIFSnkYHZe9GsjxE-IsbrxrvrfIB4hds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);